### ISSUE TITLE
Heading level links cannot be activated with keyboard

### ISSUE THREAD

**Issue by ayesha-77** [stringyland/bookmarklets#1]
**Issue description**
* Nothing happens When a keyboard user taps to a heading link and presses Enter key or Spacebar to activate. 

**Severity**
* High

**Occurs on**
* Chrome 116.0.58/JAWS 2022
* Chrome 116.0.58/Keyboard only

**How to replicate:**
1. Navigate to https://stringyland.github.io/bookmarklets/headings-correct.html
2. Activate the bookmarklet to review your page.
3. Tab to a heading level link with your keyboard. 
4. Press Enter or Spacebar to activate.
5. Notice how nothing happens, focus does not move, and no headings are highlighted. 

**Expected behaviour**
* Bookmarklet heading links should be accessible with keyboard, and something should happen when they are activated with a keyboard. For example, focus should move to the heading in the document or heading should highlight, or maybe they shouldn't be links.

**Actual behaviour**
* Nothing happens when a heading link is activated with keyboard.

**Comment by stringyland** [comment]
Update made to bookmarklet: links should now work as expected. When activated (by click, Enter or tap) they should highlight the matching heading.
